import { Model } from '.';

export const gatewayModels: Model[] = [
  // ------------------vercel models------------------
  {
    id: 'gateway:v0-1.5-md',
    name: 'v0-1.5-md',
    description:
      'Fine-tuned for everyday UI and code generation on Next.js/React projects, the same model behind v0.',
    provider: 'gateway',
    isReasoning: true,
    modalities: ['image', 'text'],
    features: [],
    modelType: 'chat',
    contextWindow: 128_000,
    priceInUSD: {
      input: 3,
      output: 15,
      per: '1M tokens',
    },
  },
  // ------------------open ai models------------------
  {
    id: 'gateway:openai/gpt-5',
    name: 'GPT-5',
    provider: 'gateway',
    actualProvider: 'openai',
    isReasoning: true,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 400_000,
    priceInUSD: {
      input: 1.25,
      output: 10,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:openai/gpt-4o',
    name: 'GPT-4o',
    provider: 'gateway',
    actualProvider: 'openai',
    isReasoning: false,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 128_000,
    priceInUSD: {
      input: 2.25,
      output: 10,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:openai/gpt-4o-mini',
    name: 'GPT-4o mini',
    provider: 'gateway',
    actualProvider: 'openai',
    isReasoning: false,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 128_000,
    priceInUSD: {
      input: 0.15,
      output: 0.6,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:openai/gpt-4.1',
    name: 'GPT-4.1',
    provider: 'gateway',
    actualProvider: 'openai',
    isReasoning: false,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 1_000_000,
    priceInUSD: {
      input: 2,
      output: 8,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:openai/gpt-4.1-mini',
    name: 'GPT-4.1 mini',
    provider: 'gateway',
    actualProvider: 'openai',
    isReasoning: false,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 1_000_000,
    priceInUSD: {
      input: 0.4,
      output: 1.6,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:openai/gpt-4.1-nano',
    name: 'GPT-4.1 nano',
    provider: 'gateway',
    actualProvider: 'openai',
    isReasoning: false,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 1_000_000,
    priceInUSD: {
      input: 0.1,
      output: 0.4,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:openai/o3',
    name: 'OpenAI o3',
    description:
      'Excels at step-by-step logic, advanced coding, and multimodal problem-solving, great for tasks requiring deep analysis.',
    provider: 'gateway',
    actualProvider: 'openai',
    isReasoning: true,
    modalities: ['text', 'image'],
    features: ['tool-calling', 'effort-control'],
    modelType: 'chat',
    contextWindow: 200_000,
    priceInUSD: {
      input: 10,
      output: 40,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:openai/o4-mini',
    name: 'OpenAI o4-mini',
    provider: 'gateway',
    actualProvider: 'openai',
    isReasoning: true,
    modalities: ['text', 'image'],
    features: ['tool-calling', 'effort-control'],
    modelType: 'chat',
    contextWindow: 200_000,
    priceInUSD: {
      input: 1.1,
      output: 4.4,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:openai/o3-mini',
    name: 'OpenAI o3-mini',
    provider: 'gateway',
    actualProvider: 'openai',
    isReasoning: true,
    modalities: ['text'],
    features: ['tool-calling', 'effort-control'],
    modelType: 'chat',
    contextWindow: 200_000,
    priceInUSD: {
      input: 1.1,
      output: 4.4,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:groq/gpt-oss-120b',
    name: 'gpt-oss-120b',
    provider: 'gateway',
    actualProvider: 'openai',
    isReasoning: true,
    modalities: ['text'],
    features: ['tool-calling', 'fast', 'effort-control', 'open-source'],
    modelType: 'chat',
    contextWindow: 131_000,
    priceInUSD: {
      input: 0.15,
      output: 0.75,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:groq/gpt-oss-20b',
    name: 'gpt-oss-20b',
    description:
      "OpenAI's fully open, 20B-parameter reasoning model with strong coding and function-calling skills.",
    provider: 'gateway',
    actualProvider: 'openai',
    isReasoning: true,
    modalities: ['text'],
    features: ['tool-calling', 'fast', 'effort-control', 'open-source'],
    modelType: 'chat',
    contextWindow: 128_000,
    priceInUSD: {
      input: 0.1,
      output: 0.3,
      per: '1M tokens',
    },
  },
  // ------------------gemini models------------------
  {
    id: 'gateway:google/gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    actualProvider: 'google',
    provider: 'gateway',
    isReasoning: false,
    modalities: ['text', 'image'],
    features: ['tool-calling', 'fast'],
    modelType: 'chat',
    contextWindow: 1_000_000,
    priceInUSD: {
      input: 0.15,
      output: 0.6,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:google/gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    actualProvider: 'google',
    provider: 'gateway',
    isReasoning: true,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 1_000_000,
    priceInUSD: {
      input: 2.5,
      output: 10,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:google/gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    actualProvider: 'google',
    provider: 'gateway',
    isReasoning: false,
    modalities: ['text', 'image'],
    features: ['tool-calling', 'fast'],
    modelType: 'chat',
    contextWindow: 1_000_000,
    priceInUSD: {
      input: 0.3,
      output: 2.5,
      per: '1M tokens',
    },
  },
  // ------------------anthropic models------------------
  {
    id: 'gateway:anthropic/claude-opus-4',
    name: 'Claude 4 Opus',
    provider: 'gateway',
    actualProvider: 'anthropic',
    isReasoning: true,
    hybridReasoning: true,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 200_000,
    priceInUSD: {
      input: 15,
      output: 75,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:anthropic/claude-opus-4.1',
    name: 'Claude 4.1 Opus',
    description:
      'Best for advanced coding, deep research and creative writing, but can be expensive.',
    provider: 'gateway',
    actualProvider: 'anthropic',
    isReasoning: true,
    hybridReasoning: true,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 200_000,
    priceInUSD: {
      input: 15,
      output: 75,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:anthropic/claude-sonnet-4-20250514',
    name: 'Claude Sonnet 4',
    provider: 'gateway',
    actualProvider: 'anthropic',
    isReasoning: true,
    hybridReasoning: true,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 200_000,
    priceInUSD: {
      input: 3,
      output: 15,
      per: '1M tokens',
    },
  },
  // ------------------meta models------------------
  {
    id: 'gateway:groq/llama-4-scout',
    name: 'Llama 4 Scout',
    provider: 'gateway',
    actualProvider: 'meta',
    isReasoning: true,
    modalities: ['text', 'image'],
    features: ['tool-calling', 'open-source', 'fast'],
    modelType: 'chat',
    contextWindow: 10_000_000,
    priceInUSD: {
      input: 0.11,
      output: 0.34,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:vertex/llama-4-maverick',
    name: 'Llama 4 Maverick',
    provider: 'gateway',
    actualProvider: 'meta',
    isReasoning: true,
    modalities: ['text', 'image'],
    features: ['tool-calling', 'open-source'],
    modelType: 'chat',
    contextWindow: 10_000_000,
    priceInUSD: {
      input: 0.2,
      output: 0.6,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:groq/llama-3.3-70b',
    name: 'Llama 3.3 70b',
    provider: 'gateway',
    actualProvider: 'meta',
    isReasoning: true,
    modalities: ['text', 'image'],
    features: ['tool-calling', 'open-source', 'fast'],
    modelType: 'chat',
    contextWindow: 128_000,
    priceInUSD: {
      input: 0.59,
      output: 0.79,
      per: '1M tokens',
    },
  },

  // ------------------xai models------------------
  {
    id: 'gateway:xai/grok-4',
    name: 'Grok 4',
    description: '',
    actualProvider: 'xai',
    provider: 'gateway',
    isReasoning: true,
    modalities: ['image', 'text'],
    features: [],
    modelType: 'chat',
    contextWindow: 256_000,
    priceInUSD: {
      input: 3,
      output: 15,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:xai/grok-3-mini',
    name: 'Grok 3 mini',
    description: '',
    actualProvider: 'xai',
    provider: 'gateway',
    isReasoning: true,
    modalities: ['image', 'text'],
    features: [],
    modelType: 'chat',
    contextWindow: 131_000,
    priceInUSD: {
      input: 0.3,
      output: 0.5,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:xai/grok-code-fast-1',
    name: 'grok-code-fast-1',
    description: '',
    actualProvider: 'xai',
    provider: 'gateway',
    isReasoning: true,
    modalities: ['image', 'text'],
    features: [],
    modelType: 'chat',
    contextWindow: 131_000,
    priceInUSD: {
      input: 0.2,
      output: 1.5,
      per: '1M tokens',
    },
  },
  {
    id: 'gateway:xai/grok-3',
    name: 'Grok 3',
    description: '',
    actualProvider: 'xai',
    provider: 'gateway',
    isReasoning: true,
    modalities: ['image', 'text'],
    features: [],
    modelType: 'chat',
    contextWindow: 131_000,
    priceInUSD: {
      input: 3,
      output: 15,
      per: '1M tokens',
    },
  },

  // ------------------ zai models------------------

  {
    id: 'gateway:zai/glm-4.5',
    name: 'GLM 4.5',
    description:
      'Open-source coding powehouse, go-to for developers who want top-tier code generation without the hefty Anthropic bill.',
    actualProvider: 'zai',
    provider: 'gateway',
    isReasoning: true,
    modalities: ['image', 'text'],
    features: [],
    modelType: 'chat',
    contextWindow: 128_000,
    priceInUSD: {
      input: 0.6,
      output: 2.2,
      per: '1M tokens',
    },
  },

  {
    id: 'gateway:zai/glm-4.5-air',
    name: 'GLM 4.5 Air',
    actualProvider: 'zai',
    provider: 'gateway',
    isReasoning: true,
    modalities: ['image', 'text'],
    features: [],
    modelType: 'chat',
    contextWindow: 128_000,
    priceInUSD: {
      input: 0.2,
      output: 1.1,
      per: '1M tokens',
    },
  },
];
