import { Model } from '.';

export const OpenAiModels: Model[] = [
  {
    id: 'openai:gpt-5',
    name: 'GPT-5',
    provider: 'openai',
    isReasoning: true,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 400_000,
    priceInUSD: {
      input: 1.25,
      output: 10,
      per: '1M tokens',
    },
  },
  {
    id: 'openai:gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    isReasoning: false,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 128_000,
    priceInUSD: {
      input: 2.25,
      output: 10,
      per: '1M tokens',
    },
  },
  {
    id: 'openai:gpt-4o-mini',
    name: 'GPT-4o mini',
    provider: 'openai',
    isReasoning: false,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 128_000,
    priceInUSD: {
      input: 0.15,
      output: 0.6,
      per: '1M tokens',
    },
  },
  {
    id: 'openai:gpt-4.1',
    name: 'GPT-4.1',
    provider: 'openai',
    isReasoning: false,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 1_000_000,
    priceInUSD: {
      input: 2,
      output: 8,
      per: '1M tokens',
    },
  },
  {
    id: 'openai:gpt-4.5',
    name: 'GPT-4.5',
    provider: 'openai',
    isReasoning: false,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 128_000,
    priceInUSD: {
      input: 75,
      output: 150,
      per: '1M tokens',
    },
  },
  {
    id: 'openai:gpt-4.1-mini',
    name: 'GPT-4.1 mini',
    provider: 'openai',
    isReasoning: false,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 1_000_000,
    priceInUSD: {
      input: 0.4,
      output: 1.6,
      per: '1M tokens',
    },
  },
  {
    id: 'openai:gpt-4.1-nano',
    name: 'GPT-4.1 nano',
    provider: 'openai',
    isReasoning: false,
    modalities: ['text', 'image'],
    features: ['tool-calling'],
    modelType: 'chat',
    contextWindow: 1_000_000,
    priceInUSD: {
      input: 0.1,
      output: 0.4,
      per: '1M tokens',
    },
  },
  {
    id: 'openai:o3',
    name: 'OpenAI o3',
    provider: 'openai',
    isReasoning: true,
    modalities: ['text', 'image'],
    features: ['tool-calling', 'effort-control'],
    modelType: 'chat',
    contextWindow: 200_000,
    priceInUSD: {
      input: 10,
      output: 40,
      per: '1M tokens',
    },
  },
  {
    id: 'openai:o4-mini',
    name: 'OpenAI o4-mini',
    provider: 'openai',
    isReasoning: true,
    modalities: ['text', 'image'],
    features: ['tool-calling', 'effort-control'],
    modelType: 'chat',
    contextWindow: 200_000,
    priceInUSD: {
      input: 1.1,
      output: 4.4,
      per: '1M tokens',
    },
  },
  {
    id: 'openai:o3-mini',
    name: 'OpenAI o3-mini',
    provider: 'openai',
    isReasoning: true,
    modalities: ['text'],
    features: ['tool-calling', 'effort-control'],
    modelType: 'chat',
    contextWindow: 200_000,
    priceInUSD: {
      input: 1.1,
      output: 4.4,
      per: '1M tokens',
    },
  },
];
